version: '3'

services:
  app:
    container_name: php1
    restart: always
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:delegated