version: '3'

services:
  app:
    container_name: php1
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:delegated
    command: git clone http://172.105.122.80:3000/Mitra/mustika.git